services:
  blog-1:
    build: .
    ports:
      - "3000:80"
    restart: "always"
  blog-2:
    build: .
    ports:
      - "3001:80"
    restart: "always"
  blog-3:
    build: .
    ports:
      - "3002:80"
    restart: "always"
